version: '3.9'

services:
  backend:
    build:
        context: ./project_manager
        dockerfile: Dockerfile
    container_name: backend_app
    image: backend_app_image
    env_file:
      - docker-config.env
    volumes:
      - ./project_manager:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
#    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --workers=2 config.wsgi --bind 0.0.0.0:8000 "
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  backend_test:
    container_name: backend_test
    image: backend_app_image
    env_file:
      - docker-config.env
    volumes:
      - ./project_manager:/app
    depends_on:
      db:
        condition: service_healthy
    profiles: [test]
    command: sh -c "python manage.py test && flake8 --ignore=501 ."

  db:
    image: postgres:13-alpine
    container_name: backend_db
    env_file:
      - docker-config.env
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  redis:
    image: redis:alpine
    container_name: backend_redis
    expose:
      - 6379
    restart: always

  celery:
    container_name: backend_celery
    image: backend_app_image
    env_file:
      - docker-config.env
    volumes:
      - ./project_manager:/app
    depends_on:
      - redis
      - backend
    command: sh -c "celery -A config worker -l info"

  celery-beat:
    image: backend_app_image
    command: celery -A config beat -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - docker-config.env
    depends_on:
      - celery

volumes:
    postgres_data:


