# Generated by Django 4.2.10 on 2024-02-27 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(choices=[(1, 'Unread'), (2, 'Read'), (3, 'Deleted')], default=1, verbose_name='Message state')),
                ('receivers', models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receivers')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
