# Generated by Django 5.0.2 on 2024-02-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_active',
        ),
    ]
