# Generated by Django 5.0.2 on 2024-02-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_message_receiver_message_receivers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receivers',
            new_name='receiver',
        ),
    ]
