# Generated by Django 5.0.2 on 2024-02-26 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_receivers_message_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receivers'),
        ),
    ]
