# Generated by Django 5.0.2 on 2024-02-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'In progress'), ('2', 'Completed'), ('3', 'Delayed'), ('4', 'Just created')], default='4', max_length=1),
        ),
    ]
