# Generated by Django 5.0.2 on 2024-02-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_member_project_team_alter_task_status_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.team'),
        ),
    ]
