# Generated by Django 5.0.2 on 2024-02-25 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_members_project_team_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeTrack',
            new_name='TimeTracker',
        ),
    ]
